# Generated by Django 4.0.1 on 2022-05-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsforrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_for_recipe', to='api.recipe', verbose_name='Рецепт'),
        ),
    ]
