# Generated by Django 4.0.1 on 2022-05-25 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow_follow_uniq_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Введены некорректные символы', regex='^[\\w.@+-]+\\Z')], verbose_name='Никнейм'),
        ),
    ]
